pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/b-chetna/git-practice.git'
            }
        }
        stage('InstallDependencies') {
            steps {
                bat 'cd project1 && pip install -r requirements.txt'
            }
        }
        stage('RunUnitTests') {
            steps {
                bat 'cd project1 && pytest test_app.py -v'
            }
        }
    }
}